### ISSUE TITLE
Dual monitor on boot not working

### ISSUE THREAD

**Issue by dalisoft** [dalisoft/Z390-I9-9900K-Hackintosh-OpenCore#7]
At boot level even after login screen dual-monitor does not work, only primary display works.

As a workaround you can **change monitor source to another and revert back to get it work**

**Comment by xantao** [comment]
Could be related to the following points:

- When and how should I use custom connectors?
- How can I change display priority?
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Radeon.en.md

**Comment by dalisoft** [comment]
Thank you for useful resource @supng 

I am seen many of them and as i work regulary and it takes a lot of my time, currently decided use Windows and back to Hackintosh on vacation (i think it's close to christmas/new year).

Thank you again, any PR is welcome

**Comment by dalisoft** [comment]
[This commit](https://github.com/dalisoft/Z390-I9-9900K-Hackintosh-OpenCore/commit/ecd6e459de5ef1a6a2dca3b98575cc48945f02a2) fixes this issue.

Thank you for tips @supng 

More info: i'm made [DSL file](https://github.com/dalisoft/Z390-I9-9900K-Hackintosh-OpenCore/blob/ecd6e459de5ef1a6a2dca3b98575cc48945f02a2/EFI/OC/ACPI/GPU-RX-470-iGPU.dsl) and tried compile but failed (idk why).
Some values are in comment for writing and some of them are copied at https://github.com/acidanthera/WhateverGreen/blob/5aa831a224a87b1633009537283e394ec9ed2dd7/Manual/reference.cpp#L86-L108 for my [GPU](https://www.techpowerup.com/gpu-specs/sapphire-rx-470-platinum-edition.b3735)
Then tried to insert these values into `DeviceProperties`, after few tests, voila it works

Note: HDMI A/B types are different.

So, it now works. Just remember to switch to HDMI source on your monitor
